#app
server:
  port: 8082
  servlet:
    context-path: /bluewhale

#开启热部署
spring:
  devtools:
    restart:
      enabled: true

---

#freemarker配置
spring:
  #freemarker配置
  freemarker:
    #是否开启模板缓存，默认为true，开发会设置为false
    cache: true
    #把HttpServletRequest的属性存放到request这个变量里面，页面上可以通过request.contextPath获取应用上下文信息
    request-context-attribute: request
    settings:
      template_update_delay: 0

---
#数据库连接
spring:
  datasource:
    url: jdbc:mysql://119.3.78.155:3306/blueWhale
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.qs.bluewhale.entity
  typeEnumsPackage: com.qs.bluewhale.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.qs.bluewhale.mapper: debug


#自定义键值对
shiro:
  password:
    salt: abc
    hashIterations: 2
    algorithmName: md5